name: "Build"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: # use it on multiple nodejs versions
        node-version: [16, 17, 18]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm build